# Build stage
FROM node:18-alpine as build
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
COPY create-env-file.sh ./
RUN npm ci
COPY . ./

ARG REACT_APP_BACKEND_HOST

RUN sh create-env-file.sh REACT_APP_BACKEND_HOST=$REACT_APP_BACKEND_HOST
RUN npm run build


# Serve stage
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
COPY --from=build /app/.env /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]