version: '3'
services:
  question-service:
    container_name: question-service
    build: 
      context: ./question_service
    environment:
      - MONGODB_URI=mongodb://mongo:27017/question_service
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - ./question_service:/usr/src/app
  
  user-service:
    container_name: user-service
    build: 
      context: ./user_service
    environment:
      PORT: 8081
      SECRET_KEY: ${SECRET_KEY}

    ports:
      - "8081:8081"
    depends_on:
      - postgres
    volumes:
      - ./user_service:/usr/src/app

  matching-service:
    container_name: matching-service
    build:
      context: ./matching_service
    environment:
      - PORT=8082
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
    volumes:
      - ./matching_service:/usr/src/app

  match-worker:
    container_name: match-worker
    build:
      context: ./match_worker
    depends_on:
      - rabbitmq
      - matching-service
    volumes:
      - ./match_worker:/usr/src/app
  
  mongo:
    container_name: mongo
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-dev-data:/data/db

  postgres:    
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_PORT: ${PG_PORT}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  postgres_data:
  mongo-dev-data:
