version: '3'
services:
  question-service:
    container_name: question-service
    build: 
      context: ./question_service
    environment:
      - MONGODB_URI=mongodb://mongo:27017/question_service
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  user-service:
    container_name: user-service
    build: 
      context: ./user_service
    environment:
      PORT: 8081
      SECRET_KEY: ${SECRET_KEY}

    ports:
      - "8081:8081"
    depends_on:
      - postgres
    volumes:
      - profile_pictures:/usr/src/app/public/profile_pictures

  matching-service:
    container_name: matching-service
    build:
      context: ./matching_service
    environment:
      - PORT=8082
    ports:
      - "8082:8082"
    depends_on:
      rabbitmq:
        condition: service_healthy

  collab-service:
    container_name: collab-service
    environment:
      PORT: 8083
    build:
      context: ./collab_service
    ports:
      - "8083:8083"

  mongo:
    container_name: mongo
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-dev-data:/data/db

  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"

  postgres:    
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_PORT: ${PG_PORT}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
volumes:
  postgres_data:
  mongo-dev-data:
  profile_pictures:
