version: '3'
services:
  question-service:
    container_name: question-service
    build: 
      context: ./question_service
    environment:
      - MONGODB_URI=mongodb://mongo:27017/question_service
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    volumes:
      - ./question_service:/usr/src/app
  mongo:
    container_name: mongo
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-dev-data:/data/db
volumes:
  mongo-dev-data:

