version: '3'
services:
  user-service:
    container_name: user-service
    build: 
      context: ./
    environment:
      PORT: 8081
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app
  
  postgres:
    container_name: postgres-user-service
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_PORT: ${PG_PORT}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: